### PR TITLE
Fixed mtail config issue

### PR DESCRIPTION
**Pull request by kdotmanoj**
solves #116

### CODE REVIEW

**Comment by bastischubert** [comment]
what do the 2 added submodules do?

**Comment by kdotmanoj** [comment]
The two counters, http_m3u8_requests_total and http_ts_requests_total, track the number of HTTP requests for M3U8 playlist files and TS media files, respectively. These are crucial for monitoring and analyzing the performance of streaming content on the webserver.

**Comment by krokodilerian** [comment]
We're asking about https://github.com/FOSDEM/infrastructure/commit/963a112ce0a8e813b8bb2889b2758ac55d7d44f4, which is part of this pull request. It add two submodules to the repo, what do they do?

**Comment by bastischubert** [comment]
@kdotmanoj : it looks like you somehow screwed up your working directory and added two submodules with this commit. 
Since we're about to move to promtail (https://github.com/FOSDEM/video/issues/46) and drop mtail i think we do not need this fix anyway. thx for the input anyway!

**Pull request closed without merging**
