### PR TITLE
Update snmp_exporter

### PR DESCRIPTION
**Pull request by SuperQ**
* Use 0.15.0.
* Add scrape job to monitor the snmp_exporter.
* Add Enum options to generator config.
* Regenerate the snmp config.
* Remove rouge AP table module, it never worked.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by krokodilerian** [comment]
I don't see a reason this isn't merged, but as doing mostly video, it doesn't feel right for me to merge it.

**Comment by RichiH** [comment]
Sorry, I totally dropped this.

@SuperQ do you want to update the PR or are you good to go?

**Comment by SuperQ** [comment]
Yes, I can go through a round of updates.

**Comment by SuperQ** [comment]
Ok, cleaned up the PR and re-generated the snmp.yml from the latest MIBs.

**Pull request merged**
