### PR TITLE
sproxy: check version, use a normal mirror

### PR DESCRIPTION
**Pull request by krokodilerian**

### CODE REVIEW

**Comment by SuperQ** [comment]
I thought that `armhf` was the same as `armv7l`. There's an easier way to translate architectures, we have to do this for Go, because the arch names don't match there either.

We can create a similar arch map [like this](https://github.com/cloudalchemy/ansible-prometheus/blob/master/vars/main.yml).

**Comment by krokodilerian** [comment]
Or we can create the same release for armv7l, etc. We can keep a ton of these and it not being a problem, and we can add new ones if needed.

If this seems ok, I can update the recipe for sproxy to create amrv7l also from armhf.

**Comment by SuperQ** [comment]
Closing in favor of #221.

**Comment by krokodilerian** [comment]
I run that mirror, so I don't consider it a random one, and I consider it better than the github one which on deployment from all boxes started dropping connections.

**Comment by SuperQ** [comment]
That doesn't make it better. IMO it makes it worse, as you are now a SPoF for the service.

**Pull request closed without merging**
