### PR TITLE
LICENSE: initial import

### PR DESCRIPTION
**Pull request by krokodilerian**
As requested in issue #296, there should be a license in here so other
projects would be ok with using the software contained in here.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by yoe** [comment]
LGTM

(I don't think GPLv3 is *necessary* for this type of project, but am not opposed to it)

**Comment by yoe** [comment]
oh, damn

I was going to add reviewers so we can see if everyone agrees, and then decided not to, and now github actually did that. Sorry for the noise... :-/

**Comment by gerryd** [comment]
I'm fine with GPLv3 if need be, but I would prefer a more liberal license, preferably MIT for code and CC-BY for content. This would also be in line with our other license policies (video content, website).

**Comment by krokodilerian** [comment]
@gerryd is there an easy way to have the two licenses for the different content, is it done with the same file, or?

**Comment by gerryd** [comment]
For our website (the only other project where we have two licenses that I know of), it is done in one LICENSE file, along with some explanation. See here: https://github.com/FOSDEM/website/blob/master/LICENSE

**Comment by krokodilerian** [comment]
This is a lot better, I think. If @markvdb has no objections, I'll copy the license file from the web, and it should be in line with the rest of FOSDEM's stuff.

**Comment by RichiH** [comment]
Copying this over makes the most sense, yes.

**Pull request merged**
