### PR TITLE
Add config for public prometheus+grafana

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by RichiH** [comment]
Grafana should listen on :80 and/or :443 instead of :3000

**Comment by brian-brazil** [comment]
This is as far as I got before heading to bed.

**Comment by SuperQ** [comment]
I've been setting things up behind apache.  This way we can have all of the
various apps listen on their whatever ports on localhost.

**Comment by SuperQ** [comment]
Yea, this has the apache setup, I'd rather not use the nightly packges, but this is probably fine for a weekend.

**Pull request merged**
